name: Test past releases

on: 
  workflow_dispatch:
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    # > Scheduled workflows run on the latest commit on the default or base branch
    # i.e. this can only run on master
    - cron:  '0 11 * * 0'
  pull_request:
    branches:
      - '*'
env:
    # Even when given -y, apt will still sometimes hang at a prompt if a package
    # has clarifications to ask; DEBIAN_FRONTEND=noninteractive prevents that,
    # This will be defined for non-debian platforms below too, but there's no harm in that.
    # (TravisCI quietly defined this on all their platforms, but we have to give it manually on GithubCI.)
    DEBIAN_FRONTEND: 'noninteractive'
    # Turns on color output for pytest. See: https://github.com/pytest-dev/pytest/issues/7443#issuecomment-656642591
    PY_COLORS: "1"
    # Disable progress bars for less verbose output
    PIP_PROGRESS_BAR: "off"
    SCT_PROGRESS_BAR: "off"

jobs:

  test_past_releases:
    name: Test past releases
    strategy:
      fail-fast: false
      matrix:
        sct_version: [ "7.0", "6.5", "6.4", "6.3", "6.2", "6.1", "6.0", "5.8", "5.7", "5.6", "5.5", "5.4", "5.3.0", "5.2.0", "5.1.0" ]
        os: [ ubuntu-latest, macos-latest, macos-15, windows-2025 ]
        os_type: [ "wsl", "native" ]
        exclude:
          # WSL is only available on Windows, so skip "ubuntu+wsl" and "macos+wsl"
          # This essentially restricts the "os_type" matrix to only parametrize the `windows` runners
          - os: ubuntu-latest
            os_type: "wsl"
          - os: macos-latest
            os_type: "wsl"
          - os: macos-15
            os_type: "wsl"
          # "native Windows" (i.e. non-WSL) support was only properly introduced in 5.7, so skip older versions
          - sct_version: "5.6"
            os: windows-2025
            os_type: "native"
          - sct_version: "5.5"
            os: windows-2025
            os_type: "native"
          - sct_version: "5.4"
            os: windows-2025
            os_type: "native"
          - sct_version: "5.3.0"
            os: windows-2025
            os_type: "native"
          - sct_version: "5.2.0"
            os: windows-2025
            os_type: "native"
          - sct_version: "5.1.0"
            os: windows-2025
            os_type: "native"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # For WSL, default to 'wsl-bash'
        #  - Note that even on WSL, we override this for steps that interact with GitHub
        # For all other platforms (i.e. wsl == false), default to `bash`
        shell: ${{ matrix.os_type == 'wsl' && 'wsl-bash {0}' || 'bash' }}

    steps:
      - uses: Vampire/setup-wsl@v5
        if: runner.os == 'Windows' && matrix.os_type == 'wsl'
        with:
          distribution: Ubuntu-24.04

      - name: Setup dependencies for WSL
        if: runner.os == 'Windows' && matrix.os_type == 'wsl'
        run: |
          # NB: this one needs sudo, so the global DEBIAN_FRONTEND doesn't get through.
          # NB: mesa-utils is needed for PyQT testing (https://github.com/Microsoft/WSL/issues/1246#issuecomment-356425862)
          sudo apt update && sudo DEBIAN_FRONTEND=noninteractive apt install -y gcc git curl mesa-utils

      - name: Setup git for WSL
        if: runner.os == 'Windows' && matrix.os_type == 'wsl'
        shell: bash
        run: |
          # Github's actions/checkout@v4 when run on Windows mangles the line-endings to DOS-style
          # but we're running Linux *on top* of Windows, so we need to not mangle them!
          # https://github.com/actions/checkout/issues/135#issuecomment-602171132
          # https://github.com/actions/runner-images/issues/50#issuecomment-663920265
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.sct_version }}

      - name: Install SCT (Unix + WSL)
        if: runner.os != 'Windows' || matrix.os_type == 'wsl'
        run: ./install_sct -y

      - name: Force Python 3.7 (Windows, SCT v5.7)
        if: runner.os == 'Windows' && matrix.sct_version == '5.7' && matrix.os_type == 'native'
        # Version 5.7-5.8's Windows installer tapped into the system python, meaning we need to set it up ourselves here
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Force Python 3.8 (Windows, SCT v5.8)
        if: runner.os == 'Windows' && matrix.sct_version == '5.8' && matrix.os_type == 'native'
        # Version 5.7-5.8's Windows installer tapped into the system python, meaning we need to set it up ourselves here
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install SCT (Windows)
        if: runner.os == 'Windows' && matrix.os_type == 'native'
        shell: cmd
        run: install_sct.bat

      - name: Update environment variables (Unix + WSL)
        if: runner.os != 'Windows' || matrix.os_type == 'wsl'
        run: |
            # NB: install_sct edits ~/.bashrc, but those environment changes don't get passed to subsequent steps in GH Actions.
            # So, we filter through the .bashrc and pass the values to $GITHUB_ENV and $GITHUB_PATH.
            # Relevant documentation: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#environment-files
            # This workaround should be replaced by https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3198#discussion_r568225392
            cat "$HOME/.bashrc" | grep "export SCT_DIR" | cut -d " " -f 2 >> $GITHUB_ENV
            cat "$HOME/.bashrc" | grep "export PATH" | grep -o "/.*" | cut -d ':' -f 1 >> $GITHUB_PATH

      - name: Update environment variables (native Windows)
        if: runner.os == 'Windows' && matrix.os_type == 'native'
        run: |
            export VERSION_TXT=$(< spinalcordtoolbox/version.txt)
            # SCT_DIR was different in the first iteration of Windows support
            if [ "${VERSION_TXT}" == "5.7" ] || [ ${VERSION_TXT} == "5.8" ]; then
              export SCT_DIR="${{ github.workspace }}"
            else
              export SCT_DIR="$USERPROFILE\sct_${VERSION_TXT}"
            fi

            # NB: I'm not sure what GHA's syntax is for cmd.exe, so we use bash to set the environment variables.
            # In a user install, the user would perform this step using the Windows environment variable changing GUI.
            echo "SCT_DIR=$SCT_DIR" >> $GITHUB_ENV
            echo "$SCT_DIR\bin" >> $GITHUB_PATH

      - name: Check dependencies
        # windows + SCT v5.7 fails with a DLL error here, but I'm not sure if that impacts the tests too, so continue
        continue-on-error: true
        run: sct_check_dependencies

      # Run tests using 'sct_testing' for all versions except v5.4
      #  -  <5.4 (sct_testing was a custom testing framework)
      #  - ==5.4 (requires special syntax, see below)
      #  -  >5.4 (sct_testing became an alias for pytest)
      - name: Run tests (UNIX + WSL)
        if: (runner.os != 'Windows' || matrix.os_type == 'wsl') && matrix.sct_version != '5.4'
        run: |
          sct_testing
      - name: Run tests (native Windows 2025)
        if: (runner.os == 'Windows' && matrix.os_type == 'native') && matrix.sct_version != '5.4'
        run: |
          # The model `seg_sc_t2star` is failing on Windows 2025, but not on other platforms.
          # It seems to produce non-deterministic outputs with varying Dice scores between runs.
          # However, this model has been retired in v7.0, and was not really used even when it
          # was available. So, we can just skip the test when running "old release" tests on Windows 2025.
          sct_testing -k 'not (test_segment_nifti and seg_sc_t2star)'

      # Run tests using `./bin/pytest` for v5.4 only
      - name: Run tests (special syntax for v5.4 only)
        if: matrix.sct_version == '5.4'
        run: |
          # Note: `bin/` isn't supported on native Windows, but SCT v5.4 only runs on Unix-like platforms anyway, so we are fine.
          ./python/envs/venv_sct/bin/pytest ./testing
